version: "3.7"
services:
    openspg:
        extends:
            file: docker-compose-no-es.yml
            service: openspg

    mysql:
        extends:
            file: docker-compose-no-es.yml
            service: mysql

    tugraph:
        extends:
            file: docker-compose-no-es.yml
            service: tugraph

    elasticsearch:
        image: elasticsearch:8.5.3
        container_name: release-openspg-elasticsearch
        ports:
            - "9200:9200"
            - "9300:9300"
        environment:
            - discovery.type=single-node
            - xpack.security.enabled=false





